# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 139, 16))
        self.label.setObjectName("label")
        self.ScanParameters = QtWidgets.QGroupBox(self.centralwidget)
        self.ScanParameters.setGeometry(QtCore.QRect(350, 510, 271, 181))
        self.ScanParameters.setObjectName("ScanParameters")
        self.btn_SCAN = QtWidgets.QPushButton(self.ScanParameters)
        self.btn_SCAN.setGeometry(QtCore.QRect(20, 140, 80, 23))
        self.btn_SCAN.setObjectName("btn_SCAN")
        self.sb_Npoints = QtWidgets.QSpinBox(self.ScanParameters)
        self.sb_Npoints.setGeometry(QtCore.QRect(20, 70, 47, 24))
        self.sb_Npoints.setMaximum(2000)
        self.sb_Npoints.setProperty("value", 10)
        self.sb_Npoints.setObjectName("sb_Npoints")
        self.sb_sample_spacing = QtWidgets.QSpinBox(self.ScanParameters)
        self.sb_sample_spacing.setGeometry(QtCore.QRect(140, 70, 47, 20))
        self.sb_sample_spacing.setMaximum(1000)
        self.sb_sample_spacing.setProperty("value", 50)
        self.sb_sample_spacing.setObjectName("sb_sample_spacing")
        self.lbl_Nsamples = QtWidgets.QLabel(self.ScanParameters)
        self.lbl_Nsamples.setGeometry(QtCore.QRect(10, 20, 81, 41))
        self.lbl_Nsamples.setWordWrap(True)
        self.lbl_Nsamples.setObjectName("lbl_Nsamples")
        self.lbl_sampleLength = QtWidgets.QLabel(self.ScanParameters)
        self.lbl_sampleLength.setGeometry(QtCore.QRect(130, 30, 91, 16))
        self.lbl_sampleLength.setObjectName("lbl_sampleLength")
        self.lbl_microns = QtWidgets.QLabel(self.ScanParameters)
        self.lbl_microns.setGeometry(QtCore.QRect(190, 70, 59, 15))
        self.lbl_microns.setObjectName("lbl_microns")
        self.btn_Clear = QtWidgets.QPushButton(self.ScanParameters)
        self.btn_Clear.setGeometry(QtCore.QRect(130, 140, 80, 23))
        self.btn_Clear.setObjectName("btn_Clear")
        self.gb_ = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_.setGeometry(QtCore.QRect(70, 530, 251, 191))
        self.gb_.setObjectName("gb_")
        self.formLayout = QtWidgets.QFormLayout(self.gb_)
        self.formLayout.setObjectName("formLayout")
        self.btn_go1 = QtWidgets.QPushButton(self.gb_)
        self.btn_go1.setObjectName("btn_go1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_go1)
        self.sb_goto1 = QtWidgets.QSpinBox(self.gb_)
        self.sb_goto1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.sb_goto1.setToolTipDuration(2)
        self.sb_goto1.setMinimum(-150)
        self.sb_goto1.setMaximum(150)
        self.sb_goto1.setSingleStep(1)
        self.sb_goto1.setProperty("value", 0)
        self.sb_goto1.setDisplayIntegerBase(10)
        self.sb_goto1.setObjectName("sb_goto1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_goto1)
        self.btn_goto2 = QtWidgets.QPushButton(self.gb_)
        self.btn_goto2.setObjectName("btn_goto2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_goto2)
        self.sb_goto2 = QtWidgets.QSpinBox(self.gb_)
        self.sb_goto2.setMinimum(-150)
        self.sb_goto2.setMaximum(150)
        self.sb_goto2.setSingleStep(5)
        self.sb_goto2.setProperty("value", 25)
        self.sb_goto2.setObjectName("sb_goto2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sb_goto2)
        self.btn_goto3 = QtWidgets.QPushButton(self.gb_)
        self.btn_goto3.setObjectName("btn_goto3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btn_goto3)
        self.sb_goto3 = QtWidgets.QSpinBox(self.gb_)
        self.sb_goto3.setMinimum(-150)
        self.sb_goto3.setMaximum(150)
        self.sb_goto3.setSingleStep(5)
        self.sb_goto3.setProperty("value", 75)
        self.sb_goto3.setObjectName("sb_goto3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sb_goto3)
        self.btn_goto3_2 = QtWidgets.QPushButton(self.gb_)
        self.btn_goto3_2.setObjectName("btn_goto3_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btn_goto3_2)
        self.sb_goto3_2 = QtWidgets.QSpinBox(self.gb_)
        self.sb_goto3_2.setMinimum(-150)
        self.sb_goto3_2.setMaximum(150)
        self.sb_goto3_2.setSingleStep(5)
        self.sb_goto3_2.setProperty("value", 100)
        self.sb_goto3_2.setObjectName("sb_goto3_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sb_goto3_2)
        self.lbl_current_pos = QtWidgets.QLabel(self.gb_)
        self.lbl_current_pos.setObjectName("lbl_current_pos")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_current_pos)
        self.curr_position = QtWidgets.QLCDNumber(self.gb_)
        self.curr_position.setSmallDecimalPoint(True)
        self.curr_position.setDigitCount(4)
        self.curr_position.setObjectName("curr_position")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.curr_position)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 30, 681, 471))
        self.widget.setObjectName("widget")
        self.sb_left = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_left.setGeometry(QtCore.QRect(70, 500, 47, 24))
        self.sb_left.setMinimum(-100)
        self.sb_left.setMaximum(120)
        self.sb_left.setObjectName("sb_left")
        self.sb_right = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_right.setGeometry(QtCore.QRect(130, 500, 47, 24))
        self.sb_right.setMaximum(200)
        self.sb_right.setProperty("value", 100)
        self.sb_right.setObjectName("sb_right")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 500, 81, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 81, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.sb_lower_limit = QtWidgets.QSpinBox(self.groupBox)
        self.sb_lower_limit.setGeometry(QtCore.QRect(20, 90, 47, 24))
        self.sb_lower_limit.setMinimum(-100)
        self.sb_lower_limit.setMaximum(100)
        self.sb_lower_limit.setProperty("value", -10)
        self.sb_lower_limit.setObjectName("sb_lower_limit")
        self.sb_upper_limit = QtWidgets.QSpinBox(self.groupBox)
        self.sb_upper_limit.setGeometry(QtCore.QRect(20, 60, 47, 24))
        self.sb_upper_limit.setMinimum(-100)
        self.sb_upper_limit.setMaximum(100)
        self.sb_upper_limit.setProperty("value", 10)
        self.sb_upper_limit.setObjectName("sb_upper_limit")
        self.lbl_limit = QtWidgets.QLabel(self.groupBox)
        self.lbl_limit.setGeometry(QtCore.QRect(10, 30, 59, 15))
        self.lbl_limit.setObjectName("lbl_limit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 20))
        self.menubar.setObjectName("menubar")
        self.menuProfilometer = QtWidgets.QMenu(self.menubar)
        self.menuProfilometer.setObjectName("menuProfilometer")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuTIlt_Correction = QtWidgets.QMenu(self.menubar)
        self.menuTIlt_Correction.setObjectName("menuTIlt_Correction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_File = QtWidgets.QAction(MainWindow)
        self.action_File.setObjectName("action_File")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionTilt_Correct = QtWidgets.QAction(MainWindow)
        self.actionTilt_Correct.setObjectName("actionTilt_Correct")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.action_Print = QtWidgets.QAction(MainWindow)
        self.action_Print.setObjectName("action_Print")
        self.menuProfilometer.addAction(self.action_File)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionLoad)
        self.menu_File.addAction(self.action_Print)
        self.menuTIlt_Correction.addAction(self.actionTilt_Correct)
        self.menubar.addAction(self.menuProfilometer.menuAction())
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuTIlt_Correction.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_go1.clicked.connect(self.sb_goto1.selectAll)
        self.btn_goto2.clicked.connect(self.sb_goto2.selectAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Laser Scan MIcrometer"))
        self.ScanParameters.setTitle(_translate("MainWindow", "Scan Parameters"))
        self.btn_SCAN.setText(_translate("MainWindow", "SCAN"))
        self.lbl_Nsamples.setText(_translate("MainWindow", "Number of Samples"))
        self.lbl_sampleLength.setText(_translate("MainWindow", "Total Distance (mm)"))
        self.lbl_microns.setText(_translate("MainWindow", "mm"))
        self.btn_Clear.setText(_translate("MainWindow", "Clear"))
        self.gb_.setTitle(_translate("MainWindow", " Motion control distance along axis (mm)"))
        self.btn_go1.setText(_translate("MainWindow", "Go"))
        self.btn_goto2.setText(_translate("MainWindow", "Go"))
        self.btn_goto3.setText(_translate("MainWindow", "Go"))
        self.btn_goto3_2.setText(_translate("MainWindow", "Go"))
        self.lbl_current_pos.setText(_translate("MainWindow", "Current Position"))
        self.label_2.setText(_translate("MainWindow", "Set X-range"))
        self.lbl_limit.setText(_translate("MainWindow", "Set Limits"))
        self.menuProfilometer.setTitle(_translate("MainWindow", "Profilometer"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuTIlt_Correction.setTitle(_translate("MainWindow", "TIlt Correction"))
        self.action_File.setText(_translate("MainWindow", "&File"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.actionTilt_Correct.setText(_translate("MainWindow", "Tilt Correct"))
        self.actionLoad.setText(_translate("MainWindow", "&Load"))
        self.action_Print.setText(_translate("MainWindow", "&Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

